print("Введите первое целое чило: ")
number_1 = int(input())
print("Введите второе целое чило: ")
number_2 = int(input())
print("Сумма чисел: ")
print(number_1+number_2)
print("Вычитание чисел: ")
print(number_1-number_2)
print("Произведение чисел: ")
print(number_1*number_2)
print("Деление чисел: ")
print(number_1/number_2)